import { v4 as uuidv4 } from "uuid";

export const SRCarltonTags = [
  {
    tag: "Title",
    data: "client 1s title",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "FirstName",
    data: "client 1s first name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "LastName",
    data: "client 1s last name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "Email",
    data: "client 1s email",
    prompt: "return {{data}} on its own.",
    uuid: uuidv4(),
  },
  {
    tag: "Age",
    data: "client 1s age",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "Occupation",
    data: "client 1s occupation",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "Employer",
    data: "client 1s employer",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "TotalAnnualEarnings",
    data: "client 1s total annual earnings",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "IsInGoodHealth",
    data: "is client 1 in good health",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "MedicalConditions",
    data: "client 1s medical conditions",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "Client1AgreesWithGeneratedRiskProfile",
    data: "does client 1 agree with the generated risk profile ",
    prompt: "return {{data}} as a boolean with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "Client1Notes",
    data: "client 1s notes",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "DependantRelationship",
    data: "client 1s relationship to their dependant",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "DependantName",
    data: "client 1s dependands namne",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "TitleClient2",
    data: "client 2s title",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "FirstNameClient2",
    data: "client 2s first name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "LastNameClient2",
    data: "client 2s last name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "AgeClient2",
    data: "client 2s age",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "OccupationClient2",
    data: "client 2s occupation",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "EmployerClient2",
    data: "client 2s employer",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "TotalAnnualEarningsClient2",
    data: "client 2s total annual earnings",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "IsInGoodHealthClient2",
    data: "is client 2 in good health",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "MedicalConditionsClient2",
    data: "client 2s medical conditions",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "Client2AgreesWithGeneratedRiskProfile",
    data: "does client 2 agree with the generated risk profile ",
    prompt: "return {{data}} as a boolean with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "Client2Notes",
    data: "client 2s notes",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "CurrentDate",
    data: "the current date",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "ReferenceNumber",
    data: "the reference number",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "BudgetNotes",
    data: "budget notes",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "MonthlyIncome",
    data: "monthly income",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "MonthlyExpenditure",
    data: "monthly expenditure",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "ProfileNotes",
    data: "profile notes",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "GoalsObjectivesNotes",
    data: "goals objectives notes",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "GoalsObjectivesDetails",
    data: "goals objectives details",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "GeneratedRiskScoreTitle",
    data: "generated risk score title",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "GeneratedRiskScoreDescription",
    data: "generated risk score description",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "WholeMarketProviderName",
    data: "whole market provider name",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
];

export const BasicReportTags = [
  {
    tag: "first_name",
    data: "first name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "last_name",
    data: "last name",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "meeting_date",
    data: "company join date",
    prompt: "return {{data}}",
    uuid: uuidv4(),
  },
  {
    tag: "company_name",
    data: "company name",
    prompt: "return {{data}} on its own.",
    uuid: uuidv4(),
  },
  {
    tag: "dob",
    data: "date of birth",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "martial_status",
    data: "martial status",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "dependants",
    data: "number of dependants",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "tax_status",
    data: "tax status",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "uptodate_will",
    data: "uptodate will in place",
    prompt: "return {{data}} as a boolean with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "state_of_health",
    data: "current state of health",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "investment_type",
    data: "investment type",
    prompt: "return {{data}} only with no other text",
    uuid: uuidv4(),
  },
  {
    tag: "investment_provider",
    data: "investment provider",
    prompt: "return {{data}}",
    uuid: uuidv4(),
  },
  {
    tag: "policy_number",
    data: "policy number",
    prompt: "return {{data}} as simply as possible with no additional text",
    uuid: uuidv4(),
  },
  {
    tag: "amount_invested",
    data: "amount invested in their investment",
    prompt: "return {{data}} as a number with no other text",
    uuid: uuidv4(),
  },
];
