name: Tests CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: npm i

      - run: npm run test:ci
